[package]
name = "tetris_macroquad"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14"
env_logger = "0.11"
log = "0.4"
macroquad = "0.4"
serde = "1.0"
tetris_game = { path = "../tetris_game" }
